### PR TITLE
[Core] fix asr resample out data len

### PR DESCRIPTION
**Pull request by zhang90501**

### CODE REVIEW

**Comment by dragos-oancea** [comment]
Could you perhaps add an unit test too ? You could look into tests/unit/ to see how they are done.

**Comment by zhang90501** [comment]
already add unit test, can we handle this pr? @dragos-oancea

**Review by andywolk — CHANGES_REQUESTED** [review]
Please enable the test in `tests\unit\Makefile.am`

**Comment by andywolk** [comment]
@zhang90501 ping

**Review by andywolk — APPROVED** [review]

**Pull request merged**
