### PR TITLE
[mod_spandsp] Compatible with the new version of spandsp.

### PR DESCRIPTION
**Pull request by azzbcc**

### CODE REVIEW

**Comment by andywolk** [comment]
Thank you. Will this work on Windows?

**Comment by azzbcc** [comment]
I don't have windows environment.

**Comment by ThomasLobker** [comment]
Thanks so much for sharing @azzbcc 

This works for me when building on Ubuntu 24.04 with the latest version of spandsp.

**Comment by pfournier** [comment]
While this patch allows FreeSWITCH to compile with the newest spandsp code base, it won't be compatible with older spandsp anymore. But furthermore, it passes a null pointer as the handler to use by spandsp which doesn't check if the handler is set before calling it, so in case of V.18 mode change, FreeSWITCH would crash with a call to null-pointer.

A more complete pull request is available at #2668.

**Pull request closed without merging**
