### PR TITLE
[mod_pgsql] Use PQcmdTuples() to get number of effected rows to support UPDATE and INSERT without RETURNING.

### PR DESCRIPTION
**Pull request by ar45**

### CODE REVIEW

**Review by crienzo — DISMISSED** [review]

**Comment by andywolk** [comment]
@ar45 Please rebase to the latest master

**Comment by ar45** [comment]
@andywolk I rebased. Can you please have a look?

**Comment by andywolk** [comment]
Yeah, looking right now.

**Review by andywolk — APPROVED** [review]

**Comment by andywolk** [comment]
Thank you for the patch!

**Pull request merged**
