### PR TITLE
FS-10367: Granted FreeSwitch permission to manage system scheduler

### PR DESCRIPTION
**Pull request by sergey-safarov**
Granted FreeSwitch permission to manage system scheduler when started as regular user

### CODE REVIEW

**Comment by sergey-safarov** [comment]
> DoTo
Later need manage FreeSwitch root permission at [start](https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1300/).

**Comment by mjerris** [comment]
is it possible to address this with something like systemd instead?

**Comment by mjerris** [comment]
> > DoTo
> > Later need manage FreeSwitch root permission at [start](https://freeswitch.org/stash/projects/FS/repos/freeswitch/pull-requests/1300/).

what does this mean?

**Comment by sergey-safarov** [comment]
> is it possible to address this with something like systemd instead?

you can use this systemd unit params
- Nice=-19
- CPUSchedulingPolicy=fifo
- CPUSchedulingPriority=1
- CapabilityBoundingSet=CAP_SYS_ADMIN

But I not sure that permission for manage threads scheduler and priority is provider to FreeSwitch process.
Need write some test module that provide functions to start thread with given scheduler and priority.

[More details](https://www.freedesktop.org/software/systemd/man/systemd.exec.html)

**Comment by sergey-safarov** [comment]
> what does this mean?

That my note to remember that want create one more PR after this resolved.

**Comment by mjerris** [comment]
please let me know if you find a systemd way to manage this.

**Comment by sergey-safarov** [comment]
I can find way if added FS commands like
```
utils thread start sheduler ${sheduler_var} priority ${priority_var} nice {nice_var}
```
If FreeSwitch able start thread, then report
```
Thread started with ${sheduler_var} priority ${priority_var} nice {nice_var}
```
If  FreeSwitch cannot start thread, then report
```
FreeSwitch cannot start thread with ${sheduler_var} priority ${priority_var} nice {nice_var}
```

**Comment by mjerris** [comment]
this seems useful for testing but it does not answer the question.  we need to validate if there is a way to do this

**Comment by sergey-safarov** [comment]
I will able validate if freeswitch will have validation tool.

**Comment by Len-PGH** [comment]
This PR is older than 6 months and requires some attention to be merged, so we’re closing this issue as inactive. If you still want this submission accepted, please make sure to update your code to the latest version (this includes FreeSWITCH, sofia-sip, libks, and any other dependencies your code touches), double check that you’re following the [submission guidelines](https://github.com/signalwire/libks/blob/master/CODING_GUIDELINES), and make any revisions/updates suggested by the team. 

We’re doing a [PR Review Day](https://mailchi.mp/freeswitch/pr-review-day) event on March 21st. You’re welcome to make the necessary changes or join with any questions. We'll have team members on hand to provide immediate feedback, work through any issues that come up, and to commit changes that pass review during the event. 

We hope to see you there! If you have any questions or feedback about this event or just want some more information, you can drop in to our [Community Slack](https://signalwire.com/developers/slack-community). 

Note: There will be a second Review Day in April if you cannot make this time.

**Pull request closed without merging**
