### PR TITLE
[mod_sofia] return status to avoid seg when digest fails

### LINKED ISSUE #1621: Segmentation fault
**Describe the bug**
Crash due to segfault while processing standard amount of traffic.

**To Reproduce**
 When user try to reregister after 5-10 minutes

**Expected behavior**
No Segfault

**Package version or git hash**
 - FreeSWITCH Version 1.10.7-release~64bit (-release 64bit)

**Trace logs**
Didn't have this enabled during crash, have syslogs:
[14602853.996241] freeswitch[21538]: segfault at 0 ip 00007f65e471a2a1 sp 00007f65def6cbe8 error 4 in libc-2.17.so[7f65e45d3000+1c4000]

**backtrace from core file**
```
(gdb) bt
#0  0x00007ff43c52c2a1 in __strcasecmp_l_avx () from /lib64/libc.so.6
#1  0x00007ff4127e4733 in sofia_reg_parse_auth (profile=profile@entry=0x1069c30, authorization=authorization@entry=0x7ff40c046f10, sip=sip@entry=0x7ff40c04fcd8, de=de@entry=0x7ff43003be10, regstr=0x7ff43aa845c1 <sip_transport_tls+1> "IP/2.0/TLS", np=np@entry=0x7ff412669450 "90a80bec-951c-44d1-9cc7-5a320b806fb3", nplen=nplen@entry=128, ip=ip@entry=0x7ff4126688d0 ["52.20.25.25",]([backtrace.log](https://github.com/signalwire/freeswitch/files/8454504/backtrace.log)) network_port=2004, v_event=v_event@entry=0x7ff4126693f0, exptime=exptime@entry=3600, regtype=regtype@entry=REG_REGISTER, to_user=to_user@entry=0x7ff40c0aba05 "1404", auth_params=auth_params@entry=0x7ff412668870, reg_count=reg_count@entry=0x7ff412668878, user_xml=user_xml@entry=0x0) at sofia_reg.c:3427
#2  0x00007ff4127e62cf in sofia_reg_handle_register_token (nua=nua@entry=0x7ff43001cac0, profile=profile@entry=0x1069c30, nh=nh@entry=0x7ff40c0669a0, sip=sip@entry=0x7ff40c04fcd8, de=de@entry=0x7ff43003be10, regtype=regtype@entry=REG_REGISTER, key=key@entry=0x7ff412669450 "90a80bec-951c-44d1-9cc7-5a320b806fb3", keylen=keylen@entry=128, v_event=v_event@entry=0x7ff4126693f0, is_nat=is_nat@entry=0x7ff4127f8224 "via received", sofia_private_p=sofia_private_p@entry=0x7ff412669cd0, user_xml=user_xml@entry=0x0, sw_acl_token=0x0) at sofia_reg.c:1614
#3  0x00007ff4127ea118 in sofia_reg_handle_sip_i_register (nua=nua@entry=0x7ff43001cac0, profile=profile@entry=0x1069c30, nh=nh@entry=0x7ff40c0669a0, sofia_private_p=sofia_private_p@entry=0x7ff412669cd0, sip=sip@entry=0x7ff40c04fcd8, de=de@entry=0x7ff43003be10, tags=tags@entry=0x7ff40c050930) at sofia_reg.c:2441
#4  0x00007ff4127ba685 in our_sofia_event_callback (event=nua_i_register, status=100, phrase=0x7ff40c050940 "Trying", nua=0x7ff43001cac0, profile=0x1069c30, nh=0x7ff40c0669a0, sofia_private=0x0, sip=0x7ff40c04fcd8, de=de@entry=0x7ff43003be10, tags=0x7ff40c050930) at sofia.c:1810
#5  0x00007ff4127c2bfb in sofia_process_dispatch_event (dep=0x7ff412669d38) at sofia.c:2253
#6  0x00007ff4127c2dd6 in sofia_msg_thread_run (thread=<optimized out>, obj=0x7ff412709ad8) at sofia.c:2302
#7  0x00007ff43dc958d0 in dummy_worker (opaque=0x10511a0) at threadproc/unix/thread.c:151
#8  0x00007ff43ce8fea5 in start_thread () from /lib64/libpthread.so.0
#9  0x00007ff43c4e39fd in clone () from /lib64/libc.so.6
```

### PR DESCRIPTION
**Pull request by seven1240**
fixes #1621

### CODE REVIEW

**Review by dragos-oancea — APPROVED** [review]

**Comment by andywolk** [comment]
Why do tests fail after that change?

**Comment by seven1240** [comment]
I dont' think it's related to this patch, can we re-trigger the test?

**Comment by seven1240** [comment]
@andywolk https://github.com/signalwire/freeswitch/pull/1628/commits/ac2f9a6e63416e565019fe401d3c09e71344a6be looks like failed the same way.

**Comment by andywolk** [comment]
See https://public-artifacts.signalwire.cloud/drone/signalwire/freeswitch/450/log_run-tests_src!mod!endpoints!mod_sofia!test!test_sofia_funcs.sh.html

**Comment by seven1240** [comment]
sorry, I posted the wrong link: I mean this one: https://github.com/signalwire/freeswitch/pull/1628

https://public-artifacts.signalwire.cloud/drone/signalwire/freeswitch/453/log_run-tests_src!mod!endpoints!mod_sofia!test!test_sofia_funcs.sh.html

drone 453 has a 8/10, and this one has a 1/10 success. but pattern looks similar.

**Comment by seven1240** [comment]
https://github.com/signalwire/freeswitch/pull/1750/files

**Pull request closed without merging**
