### PR TITLE
Combine the master and base docker images for an updated & minimized docker image that can be auto-built

### PR DESCRIPTION
**Pull request by king-dopey**
Most of the concepts are taken from the docker images in the master and base_image folders. It's now all done in one Dockerfile, using buildkit. It also includes build hooks so the Token can be added as an environment variable, on Docker Hub, for automated builds and security scans.
Other enhancements to the updated docker image:
1) Moved to su-exec (gosu in Debian flagged vulnerable)
2) Fixed the make_min_archive.sh and repurposed it to make_root_fs.sh
3) Increased the complexity of the default generated password
4) Updated the sound versions, for download
5) Updated to the latest busybox
6) Corrected ca-certificates, so Curl functions properly (including internally to freeswitch)
7) Added curl

This is currently being auto-built, upon commit at https://hub.docker.com/r/dheaps/freeswitch. (fork is also auto-synced)

### CODE REVIEW

**Comment by king-dopey** [comment]
> Unit-tests failed: https://public-artifacts.signalwire.cloud/drone/signalwire/freeswitch/1652/artifacts.html

It looks like this failed due to my last minor commit, after the PR, but the commit itself would actually have no impact on the unit test.

**Comment by king-dopey** [comment]
This PR says this was merged but it was not. The force pushed mentioned above caused a conflict and disabled git merge fast forward. I created a merge commit, so things can actually be merged.

**Comment by andywolk** [comment]
Since this PR did not have a change after (due to) a force-push made earlier it was automatically marked as merged by GitHub.
Just a suggestion: in the future try making a branch in your fork, do the work in the branch, and PR from that branch other than from your fork's master.

**Comment by king-dopey** [comment]
I agree; I went against my own advise by doing that. In this case, the issue was the the pull app. I wanted it to keep upstream changes in sync, but it just re-based, causing an issue. I disabled the app to prevent that in the future. I'll reset, squash, etc. to clean up the merge commits and create a new PR.

**Pull request merged**
