### PR TITLE
FIX parse config param "profile" and "level" in mod_av

### PR DESCRIPTION
**Pull request by ros-tel**
There was a replacement in the loop with default values

### CODE REVIEW

**Comment by seven1240** [comment]
it is covered in https://github.com/signalwire/freeswitch/pull/824/files , can you also try that patch?

**Comment by ros-tel** [comment]
> it is covered in https://github.com/signalwire/freeswitch/pull/824/files , can you also try that patch?

Faced the problem of incorrect application of the config as part of solving another problem (lack of fmtp for h264 [h264-default-fmtp](https://github.com/ros-tel/freeswitch/tree/h264-default-fmtp)) 
Therefore, I made a separate pull request.

I don't even know how to check your patch.
The only softphone that I was running under Linux with h264 Blink support and it does not decode the incoming stream (Linphone VP8> FS> H264 Blink).
What exactly is the problem I cannot figure out.

**Comment by sergey-safarov** [comment]
In my use case, I also faced with not proper config parsing.
I wrote the same patch for this issue.
https://github.com/sergey-safarov/freeswitch/commit/a5f757ba8316e072174fc73000c927ea5a404c97

So, please merge.

**Comment by dragos-oancea** [comment]
please add prefix "[mod_av]" to commit message.

**Comment by ros-tel** [comment]
#1495

**Pull request closed without merging**
