### PR TITLE
Add configuration for LGTM

### PR DESCRIPTION
**Pull request by stweil**
This configuration enables the C/C++ analyzer.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
See issue #601. If I got the required packages right, this should fix the C/C++ build for LGTM and allow it to analyze the code.

**Comment by stweil** [comment]
I was wrong: it is possible to [test the LGTM configuration](https://lgtm.com/help/lgtm/requesting-test-build-project). The [result](https://lgtm.com/logs/86fe29de3ef6905d82f9de9dcc413495158e9c43/lang:cpp) now works, so this PR is ready for merging.

I had to ignore a remaining build failure:

    [build] Makefile:963: *** You must install libks to build mod_signalwire.  Stop.

As far as I know `libks` is not available for Ubuntu eoan, so I don't know how this could be fixed.

**Comment by stweil** [comment]
> As far as I know libks is not available for Ubuntu eoan, so I don't know how this could be fixed.

Rules for `libks` and `signalwire-c` are now included.

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by stweil** [comment]
LGTM was bought by Microsoft and no longer provides its services, so this pull request is no longer useful.
The LGTM checks are now provided by GitHub. Just enable them in the project settings.

**Pull request closed without merging**
