### PR TITLE
[Build-System] freeswitch.spec update

### PR DESCRIPTION
**Pull request by sergey-safarov**
Please check commit messages for an update details

### CODE REVIEW

**Comment by s3rj1k** [comment]
@sergey-safarov I am not sure that putting commits below in a single PR is a good idea:

- https://github.com/signalwire/freeswitch/pull/1032/commits/9e1a0fe233f21c193cdf8a5ebd527a17fa13fe60
- https://github.com/signalwire/freeswitch/pull/1032/commits/c8219c3ecf118cc210d1bd9423e5284037adb46e
- https://github.com/signalwire/freeswitch/pull/1032/commits/59425783d1abe0a7fa6242bd588419fc4ea7bf55

Please move this commits out to 3 separate PRs.

**Comment by sergey-safarov** [comment]
@s3rj1k PR updated.
Commits removed from this PR

**Comment by s3rj1k** [comment]
LGTM

**Review by s3rj1k — APPROVED** [review]

**Comment by sergey-safarov** [comment]
@andywolk could you look at this PR?

**Comment by andywolk** [comment]
I need a few to test this

**Review by andywolk — APPROVED** [review]

**Pull request merged**
