### PR TITLE
[Build-System] Rename package format-mod-opusfile to format-opusfile on CentOS

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by dragos-oancea** [comment]
the format is actually "opus"

**Review by dragos-oancea — APPROVED** [review]

**Comment by sergey-safarov** [comment]
Should I rename it to `format-opus`?

**Comment by dragos-oancea** [comment]
no, better like this so it's not confused with the codec

**Comment by sergey-safarov** [comment]
@andywolk what are the next steps for this PR?

**Review by dragos-oancea — APPROVED** [review]

**Review by andywolk — APPROVED** [review]

**Pull request merged**
