### PR TITLE
FS-11587: Fixed hardcoded uuid length in msrp_find_uuid function

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by mjerris** [comment]
can you provide reference in spec to what uuid should be please

**Comment by sergey-safarov** [comment]
Are you want reference to uuid length?
My use case is kazoo installations.
Kazoo defines own ID in dialplan and later MSRP messages cannot be route because length of custom uuid and default is different.

**Comment by mjerris** [comment]
looking to confirm in msrp spec if you can have different length uuid or not

**Comment by sergey-safarov** [comment]
please check [RFC4975](https://tools.ietf.org/html/rfc4975#section-4)
Here
```
To-Path: msrp://biloxi.example.com:12763/kjhd37s2s20w2a;tcp
```
UUID here "kjhd37s2s20w2a" shorted then 36 char sting.

**Comment by mjerris** [comment]
ok so that looks good.  Please add a unit test for this.

**Comment by sergey-safarov** [comment]
I cannot create test unit.

**Comment by mjerris** [comment]
please re-open when you are able to add a unit test for this.

**Comment by mjerris** [comment]
for reference, some of our current unit tests:

https://github.com/signalwire/freeswitch/tree/master/tests/unit

https://github.com/signalwire/freeswitch/tree/master/src/mod/applications/mod_http_cache/test

**Pull request closed without merging**
