### PR TITLE
[mod_openh264] Fix stap-a size issue and add unit test.

### PR DESCRIPTION
**Pull request by paxc**
Fix issue#205 and add some test cases.
Case 1: Non aggregated packets decoding
Case 2: STAP-A  decoding

### CODE REVIEW

**Comment by seven1240** [comment]
freeswitch.xml.fsxml  is generated file can you remove that and put in .gitignore ?

and also can you add prefix `[mod_openh264]` to the commit message?

Thanks.

**Comment by paxc** [comment]
thank you, done.

**Comment by seven1240** [comment]
can you squash into one commit and prefix with `[mod_openh264]` ? check other recent commits to to see how it works.

**Comment by paxc** [comment]
Sure, squashing done

**Comment by paxc** [comment]
What’s next? Seems it still needs someone’s approval before merge, who can help to do it?

**Comment by andywolk** [comment]
Ok. I force updated. Enabled tests on Drone. Let's see how it goes.

**Comment by andywolk** [comment]
```
Dead store	Dead assignment	mod_openh264.cpp	buffer_h264_nalu	283	1
Dead store	Dead assignment	mod_openh264.cpp	buffer_h264_nalu	276	1
Dead store	Dead assignment	mod_openh264.cpp	buffer_h264_nalu	247	1
Dead store	Dead assignment	mod_openh264.cpp	buffer_h264_nalu	246	1
```

**Comment by seven1240** [comment]
Looks like I don't have permission for the branch. @andywolk @paxc can you merge this one? https://github.com/paxc/freeswitch/pull/1

**Comment by paxc** [comment]
Neither I have the permission, sorry

发自我的iPhone

**Comment by andywolk** [comment]
Not a problem. paxc#1 can be closed now.

**Pull request merged**
