### PR TITLE
ESL adjustments for PHP 7+

### PR DESCRIPTION
**Pull request by cdosoftei**
The current ESL PHP extension setup is targeting the PHP 5.x ecosystem, which has been deprecated since.

This PR addresses the compatibility aspect by realigning the extension with PHP 7.x; the setup has been successfully tested against the current recommended distribution (Debian Buster), e.g.

```Dockerfile
FROM debian:buster

RUN apt-get update && apt-get install -yq gnupg2 wget lsb-release git
RUN wget -O - https://files.freeswitch.org/repo/deb/debian-release/fsstretch-archive-keyring.asc | apt-key add -

RUN echo "deb http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" > /etc/apt/sources.list.d/freeswitch.list
RUN echo "deb-src http://files.freeswitch.org/repo/deb/debian-release/ `lsb_release -sc` main" >> /etc/apt/sources.list.d/freeswitch.list

RUN apt-get update

RUN apt-get build-dep -yq freeswitch

RUN apt-get install -yq php php-dev

WORKDIR /usr/src
RUN git clone --depth 1 --branch php7-esl https://github.com/cdosoftei/freeswitch.git

WORKDIR /usr/src/freeswitch
RUN ./bootstrap.sh -j
RUN ./configure
RUN make
RUN make install

WORKDIR /usr/src/freeswitch/libs/esl
RUN make phpmod

WORKDIR /usr/src/freeswitch/libs/esl/php
RUN make install

RUN sed -i -e 's/enable_dl = Off/enable_dl = On/g' /etc/php/7.3/cli/php.ini
```

The PR should also address this issue https://github.com/signalwire/freeswitch/issues/24

### CODE REVIEW

**Comment by mjerris** [comment]
@andywolk check this out.  We probably want to re-swig from our standard to keep changes consistent with our swig version

**Comment by cdosoftei** [comment]
3.0.12 is the swig version shipped with Buster but yes, I definitely see consistency concern with respect to the other supported languages. I can adjust the PR with the 3.0.2 output (so it's in sync with the rest of the languages line up) so this update only touches PHP specific aspects, leaving the swig version upgrade for a future PR.

**Comment by fdl33333** [comment]
AMAZING.. I've been fighting with this for over a year .. Thank you so much!

**Comment by andywolk** [comment]
@mjerris swig `3.0.10` does not support `php7` plus as I can see in https://github.com/signalwire/freeswitch/blob/master/build/swigall.sh
`make swigall` (from root) does not touch `esl/php` at all.

Reswig made by this PR does reflect the latest changes so I'm approving.

**Pull request merged**
