### PR TITLE
Broken windows

### PR DESCRIPTION
**Pull request by grmt**
make FS build and run on (at least) windows 10
used the latest updated Visual Studio 2017, so you want to update your VS installation
not sure what the agreed vcxproj file format is, I "dos2unix"-ed the ones I changed, so no BOF and only <LF>

### CODE REVIEW

**Comment by andywolk** [comment]
Can't reproduce

**Comment by andywolk** [comment]
That's a breaking PR.
Please try installing Windows 10 SDK v10.0.17134 and see if that helps.
We would also like to not stay with VS 2017 but move to Visual Studio 2019, that's on my plate already.

**Comment by grmt** [comment]
Did you try updating VS207 and building and running and **interactively** look at error messages, recently? If you don't run it, and don't compile mod_http_cache you might not have issues.

**Comment by grmt** [comment]
I actually ported everything to  VS2019

**Pull request closed without merging**
