### PR TITLE
[mod_verto] Handle short read from websocket. This fixes an interop problem with iOS 15.

### PR DESCRIPTION
**Pull request by crienzo**

### CODE REVIEW

**Review by andywolk — DISMISSED** [review]

**Review by olofssonanton — DISMISSED** [review]

**Review by olofssonanton — APPROVED** [review]

**Review by andywolk — APPROVED** [review]

**Comment by prlanzarin** [comment]
Sorry for the pull request hijacking, but I have a question: wouldn't sofia's WS transport be affected by the same interop issue?

**Comment by crienzo** [comment]
it would!

**Comment by mariogasparoni** [comment]
Hi @crienzo , would you be willing to patch sofia's WS too ?

I can send a PR for that, if this is not in your roadmap.

Thanks in advance.

**Comment by crienzo** [comment]
I'll probably forget- if you could port the change over to sofia we can review and merge it.

**Comment by mariogasparoni** [comment]
sure

**Comment by mariogasparoni** [comment]
Hi @crienzo , here it is: https://github.com/freeswitch/sofia-sip/pull/94

Tested with multiple iOS devices, this fixed the problem for us.

**Comment by olofssonanton** [comment]
Hey again @crienzo! It seems like this fix is not included in v1.10.7.

We noticed that Verto's websocket implementation was [moved to libks](https://github.com/signalwire/freeswitch/commit/ed9851666615d283effb76edc7028cc08b07eff9), but libks does not include [this fix](https://github.com/signalwire/libks/pull/117) in [v1.10.7](https://github.com/signalwire/libks/commits/v1.7.0), only on [master](https://github.com/signalwire/libks/commits/master).

**Comment by crienzo** [comment]
I asked @andywolk to make a new release of libks

**Comment by andywolk** [comment]
libks updated https://github.com/signalwire/homebrew-signalwire/pull/8

**Comment by andywolk** [comment]
@olofssonanton can you give that a try?

**Comment by olofssonanton** [comment]
@andywolk Will do, thanks!

**Comment by olofssonanton** [comment]
@andywolk I can confirm that libks version 1.8.0 solves the issue!

**Pull request merged**
