### PR TITLE
[mod_event_socket] Fix hangup race with listener_thread of socket application in async mode

### PR DESCRIPTION
**Pull request by andywolk**

### CODE REVIEW

**Comment by bee-jarvis** [comment]
hi please check dump file
[20200516T181203Z-bt.txt](https://github.com/signalwire/freeswitch/files/4638998/20200516T181203Z-bt.txt)

**Comment by zek** [comment]
Is this somehow related to https://github.com/signalwire/freeswitch/issues/580

**Comment by bee-jarvis** [comment]
First crash:
Fscrashed with load 1700 + calls in conference,  i have updated with mentioned code above.
https://github.com/bee-jarvis/FSCrashes/blob/master/20200518T055728Z-bt.txt

Second Crash:
https://github.com/bee-jarvis/FSCrashes/blob/master/20200518T070147Z-bt.txt
Senario:
more than 3 conferences created with 900+ members given conference <CONFNAME> hup all and immediately initiated conference call, or tried to execute fs commands.
Result: crashed.  calls were not released.

**Comment by andywolk** [comment]
@bee-jarvis What exactly do you do to reproduce this?

**Comment by andywolk** [comment]
@bee-jarvis Please try compiling with `./configure --enable-address-sanitizer`. It will log memory errors when running.
OR another option is to run under `valgrind`

**Comment by bee-jarvis** [comment]
@andywolk I am doing calls with event socket and adding into conference more than 900+  members i have created 3 conferences and  made conference hup all and immediately  trying to make another conference call.

**Comment by andywolk** [comment]
@bee-jarvis Let's move our discussion to a separate issue. Seems like your core dumps are unrelated to mod_event_socket.

**Pull request merged**
