### PR TITLE
Fix some typos (most found by codespell)

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by dragos-oancea** [comment]
it's hard to review something like this (31 files) . you could perhaps split this in multiple PRs . And do the docs and configs, not the code.

**Comment by stweil** [comment]
It's much easier to review if you hide whitespace changes (option under Files changed / * in GitHub) as this suppresses the changed line endings.

**Review by emcgee — DISMISSED** [review]
@dragos-oancea I took a look through these just to validate the language updates and ensure they are limited to comment blocks that don't reference code. Everything look A-👌

**Comment by dragos-oancea** [comment]
@stweil , can you please rebase ?  it's in conflict

**Comment by stweil** [comment]
@dragos-oancea, it's rebased now.

**Review by dragos-oancea — APPROVED** [review]

**Review by emcgee — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
