### PR TITLE
[mod_kazoo] Fix building (map to list changes)

### PR DESCRIPTION
**Pull request by fx02**

### CODE REVIEW

**Comment by lazedo** [comment]
@fx02 what’s the purpose of this?

**Comment by fx02** [comment]
For me, mod_kazoo will not build without this fix.

**Comment by lazedo** [comment]
What otp version are you using? JSON encoding is done with tupple or map. You need a otp version that supports maps

**Comment by fx02** [comment]
You mean this? erlang-otp_mibs-R16B-03.18.el7.x86_64

**Comment by lazedo** [comment]
You need an otp version that supports maps, at least otp17.

**Comment by fx02** [comment]
thanks, will look into that

**Pull request closed without merging**
