### PR TITLE
[core] fix session deadlock  (#2290)

### PR DESCRIPTION
**Pull request by cdevelop**
https://github.com/signalwire/freeswitch/issues/2290

### CODE REVIEW

**Comment by cdevelop** [comment]
@seven1240  Teacher Du and I explained this issue in detail.

**Comment by seven1240** [comment]
@andywolk cdeveop has a system which left 3-10 dead locked channels per day, which could be fixed by this patch.

Review the patch, it looks like the read_frame parts are fine as the message will be processed on the next read. But I'm worrying about the write parts. What if this happens on a sendonly channel that never has read? or on a App which never read but write ( I don't know such an App in my head though). So the message will never be processed.

Best to find out the root cause of the dead lock instead of the work around I think.

**Comment by bferreirq** [comment]
Hello, any news about this commit ?

**Comment by KerryRJ** [comment]
I have an installation where 30-40 inbound and outbound calls are getting deadlocked on a daily basis, and the call center agent connected to the deadlocked call also gets stuck, until a restart or the extension leg of the call is hung up.

#2387 and #2390 did not resolve the the deadlocks nor the stuck call center agent.

This fix has stopped all deadlocks and subsequently no stuck call center agents.

**Comment by televoicepl** [comment]
> I have an installation where 30-40 inbound and outbound calls are getting deadlocked on a daily basis, and the call center agent connected to the deadlocked call also gets stuck, until a restart or the extension leg of the call is hung up.
> 
> #2387 and #2390 did not resolve the the deadlocks nor the stuck call center agent.
> 
> This fix has stopped all deadlocks and subsequently no stuck call center agents.

same problem in my instance. 
1.10.11 and 1.10.10 is affected. 1.10.9 is ok
Random calls are dead and only core restart helps.

**Comment by shaunjstokes** [comment]
This fix has fixed all deadlocks and stuck calls in our environment.

#2372 and #2390 did not fix the issue.

**Comment by bfroemel** [comment]
I can also report that this patch fixes a similar issue with stuck channels and stuck call center agents in my installation.

**Comment by boteman** [comment]
Why not make it pass the Unit Tests so that it can be merged? Many people seem to be experiencing this problem.

**Comment by televoicepl** [comment]
@jakubkarolczyk can you check it?

**Comment by gregoriusus** [comment]
Can I bump this thread. This issue is real problem and a lot of people have this issue...

**Comment by boteman** [comment]
Yesterday on Office Hours I asked about this and the related tickets which exhibit a similar problem. BKW said that it is a much deeper problem than is solved by the proposed patch and that they are refarming the code to solve everything at once. So it is a bigger effort than we thought, no ETR.

**Comment by hhadzem** [comment]
Is there any progress/update related to this issue?

**Comment by zrd740** [comment]
I upgraded several servers from FreeSWITCH 1.10.8 to 1.10.12. This error showed up and it's creating dozens of stuck calls per day, as well as numerous client complaints on a daily basis. 1.10.8 does not have the issue. Is there any update on this, it seems like a problem that has been going on for a long time? FusionPBX support said thie solution to the problem is to apply this patch and compile from source as a resolution to the problem. I have wanted to use the signalwire packages on debian, but they do not work due to this issue. If we can't get a solution to this I'll need to start compiling from source.

**Comment by zrd740** [comment]
We've resolved the issue by migrating away from prebuilt packages and compiling FS from source with this patch, and it works perfectly. However, I'm disappointed that after almost a year, this hasn't been included in the release despite its impact on many users.

**Comment by boteman** [comment]
My understanding from what the core developers have said is that this ticket and at least 3 others are a combination of problems deep down in the core that require extensive re-farming of source code to correct. They found some long-standing bugs in the process and aim to correct all of them in this effort. This patch works for some, but not others, and that is why. I'm as anxious as you for a permanent fix.

**Comment by jakubkarolczyk** [comment]
Fixed in https://github.com/signalwire/freeswitch/pull/2619

**Pull request closed without merging**
