### PR TITLE
[mod_callcenter] fix leak

### PR DESCRIPTION
**Pull request by seven1240**

### CODE REVIEW

**Review by crienzo — DISMISSED** [review]

**Comment by crienzo** [comment]
@andywolk this is OK

**Review by andywolk — CHANGES_REQUESTED** [review]
Does not look right to me.
@seven1240 Please take a look at lines 
https://github.com/signalwire/freeswitch/blob/795f41e40c9348d298f4f33467e70ba77dbc7572/src/mod/applications/mod_callcenter/mod_callcenter.c#L1549
and https://github.com/signalwire/freeswitch/blob/795f41e40c9348d298f4f33467e70ba77dbc7572/src/mod/applications/mod_callcenter/mod_callcenter.c#L4344

**Comment by andywolk** [comment]
Btw zstr() does not warn if a pointer is an empty string "" (not NULL) so switch_safe_free() may be reasonable here (unless allocated in a pool):
```
	if (zstr(globals.cc_instance_id)) {
		switch_safe_free(globals.cc_instance_id); // <----
		globals.cc_instance_id = strdup("single_box");
```

**Comment by crienzo** [comment]
I'll fix it

**Review by crienzo — APPROVED** [review]

**Pull request merged**
