### PR TITLE
FS-8209: Implemented transfer endpoint

### PR DESCRIPTION
**Pull request by sergey-safarov**

### CODE REVIEW

**Comment by mjerris** [comment]
what is the purpose of this module that can not be handled already today?

**Comment by mjerris** [comment]
please add unit tests for this new functionality before we review this

**Comment by sergey-safarov** [comment]
> what is the purpose of this module that can not be handled already today?

That allow change user settings in database directory table and not change dialpaln to create callforward extension for given user.

I not able create test unit.

**Comment by mjerris** [comment]
please reopen when you are able to add unit tests for this addition

**Comment by mjerris** [comment]
for reference, some of our current unit tests:

https://github.com/signalwire/freeswitch/tree/master/tests/unit

https://github.com/signalwire/freeswitch/tree/master/src/mod/applications/mod_http_cache/test

**Pull request closed without merging**
